- contracts/mock/Mock3CoinStrategy.sol
- contracts/mock/MockStrategy.sol
- contracts/strategy/BaseClaimableStrategy.sol
- contracts/strategy/BaseStrategy.sol
- contracts/strategy/IStrategy.sol
- contracts/vault/Vault.sol
- contracts/vault/VaultAdmin.sol
- package.json
- add virtual fun :getOutputsInfo()
- add outputCode param in repay()、withdrawFrom3rdPool()
> BaseStrategy： Support specify token output.

- contracts/exchanges/ExchangeAggregator.sol
- contracts/exchanges/IExchangeAdapter.sol
- contracts/exchanges/IExchangeAggregator.sol
- contracts/exchanges/adapters/TestAdapter.sol
- contracts/library/NativeToken.sol
- contracts/mock/MockVault.sol
- contracts/strategy/IStrategy.sol
- contracts/vault/IVault.sol
- contracts/vault/Vault.sol
- contracts/vault/VaultAdmin.sol
- contracts/vault/VaultStorage.sol
- test/strategy/mock-strategy-test.js
- test/vault/index.js
Optimize remove strategy and redemption from strategy
> Optimize remove strategy and redemption from strategy

- contracts/exchanges/IExchangeAdapter.sol
- contracts/vault/Vault.sol
- package.json
> fix endAdjustPosition bug

- contracts/vault/IVault.sol
- contracts/vault/Vault.sol
- package.json
- test/vault/index.js
> add vault multicall

- contracts/vault/IVault.sol
- contracts/vault/Vault.sol
- package.json
- test/vault/index.js
> remove multicall

- contracts/vault/Vault.sol
optimize vault strategy totaldebt
> optimize vault strategy totalDebt

- contracts/vault/IVault.sol
- contracts/vault/Vault.sol
- contracts/vault/VaultAdmin.sol
- contracts/vault/VaultStorage.sol
- test/vault/index.js
remove nouser var and function
> remove nouse code

- contracts/exchanges/ExchangeAggregator.sol
- contracts/exchanges/IExchangeAggregator.sol
- contracts/harvester/Harvester.sol
- contracts/harvester/IHarvester.sol
- contracts/strategy/BaseStrategy.sol
- contracts/strategy/IStrategy.sol
- contracts/token/PegToken.sol
- contracts/vault/IVaultBuffer.sol
- contracts/vault/Vault.sol
- contracts/vault/VaultAdmin.sol
- contracts/vault/VaultBuffer.sol
code formate and clean no use code
> code formate and clean no use code

- contracts/vault/VaultStorage.sol
- package.json
1 rename local variables on missed events
2 change version from "1.6.0-alpha1“ to "1.6.0-alpha2“
> refactor: rename local variables on missed events

- contracts/token/PegToken.sol
- contracts/vault/IVault.sol
> optimize pegtoken var name

- contracts/vault/Vault.sol
- package.json
> fix new and old asset bug

- contracts/exchanges/ExchangeAggregator.sol
- contracts/exchanges/IExchangeAggregator.sol
- contracts/vault/IVault.sol
- contracts/vault/Vault.sol
- contracts/vault/VaultStorage.sol
- test/vault/index.js
1、optimze exchange aggregator（batch swap）
2、optimze vault burd（remove exchage）
> optimze exchange aggregator and vault burd

- contracts/exchanges/ExchangeAggregator.sol
opimize exchangeAggregator swap
> opimize exchangeAggregator swap

- contracts/vault/Vault.sol
> fix report bug

- contracts/vault/IVault.sol
- contracts/vault/Vault.sol
- package.json
- test/vault/index.js
> add get pegtoken price

- contracts/access-control/AccessControlProxy.sol
- package.json
fix access-control deploy error.
> use _grantRole replace _setupRole.

- contracts/harvester/Harvester.sol
- contracts/vault/Vault.sol
- package.json
1、fix havester safeApprove bug
1、fix vault safeApprove bug
> fix safeApprove bug

- contracts/exchanges/ExchangeAggregator.sol
- package.json
> fix badsign

- contracts/strategy/IStrategy.sol
- contracts/vault/Vault.sol
- contracts/vault/VaultStorage.sol
> refactor: add and modify comments

- contracts/vault/IVault.sol
- contracts/vault/Vault.sol
- contracts/vault/VaultAdmin.sol
- contracts/vault/VaultStorage.sol
- package.json
> add reportByKeeper in vault

- contracts/access-control/IWhitelist.sol
- contracts/access-control/Whitelist.sol
- contracts/exchanges/ExchangeAggregator.sol
- contracts/mock/Mock3CoinStrategy.sol
- contracts/mock/MockStrategy.sol
- contracts/vault/IVault.sol
- contracts/vault/Vault.sol
- contracts/vault/VaultAdmin.sol
- test/access/whitelist-test.js
- test/vault/index.js
> fix vault  audit bug

- contracts/token/PegToken.sol
- contracts/vault/VaultBuffer.sol
- test/token/pegtoken-test.js
> refactor: avoid approve race condition

- contracts/exchanges/ExchangeAggregator.sol
> fix reaudit b4

- contracts/harvester/Harvester.sol
- contracts/harvester/IHarvester.sol
- contracts/library/IterableSellInfoMap.sol
- contracts/mock/Mock3CoinStrategy.sol
- contracts/mock/MockStrategy.sol
- contracts/strategy/IStrategy.sol
- contracts/test/Harvester/Harvester.t.sol
- contracts/test/vault/Vault.t.sol
refactor harvester for  unified strategy for reward selling and reinvestment
> harvester refactor

- contracts/exchanges/ExchangeAggregator.sol
- contracts/mock/Mock3CoinStrategy.sol
- contracts/test/vault/Vault.t.sol
- contracts/vault/Vault.sol
sync b4 modify and modify radio zero define
> sync b4 modify and modify radio zero define

- contracts/harvester/Harvester.sol
- contracts/harvester/IHarvester.sol
- contracts/test/harvester/Harvester.t.sol
- package.json
> udpate Harvester

- contracts/test/vault/Vault.t.sol
- contracts/vault/IVault.sol
- contracts/vault/Vault.sol
- package.json
add return actual receive amount value
> add return actual receive amount value

- contracts/price-feeds/custom/CustomFrxEthPriceFeed.sol
- contracts/price-feeds/custom/CustomSEthPriceFeed.sol
- contracts/price-feeds/custom/CustomSfrxEthPriceFeed.sol
- contracts/price-feeds/custom/CustomWstEthPriceFeed.sol
- contracts/test/price-feeds/ValueInterpreter.t.sol
- foundry.toml
- hardhat.config.js
- package.json
add sfrxETH ,frxETH ,sETH oracle price
> add sfrxETH ,frxETH ,sETH oracle price

- contracts/vault/Vault.sol
- package.json
optimize vault report and adjust
> optimize vault report and adjust

- contracts/vault/IVault.sol
- contracts/vault/Vault.sol
Vault redeem method return redeemed asserts and amount info.
> feature:vault redeem add return value

- contracts/price-feeds/custom/CustomFrxEthPriceFeed.sol
- contracts/price-feeds/custom/CustomSEthPriceFeed.sol
- contracts/price-feeds/custom/CustomSfrxEthPriceFeed.sol
- contracts/price-feeds/custom/CustomWstEthPriceFeed.sol
- package.json
fix seth frxeth sfrxeth wsteth price in usd
> fix seth frxeth sfrxeth wsteth price in usd
